spring:
  jpa:
    properties:
      hibernate:
        search:
          backend:
            uris: http://localhost:9200
    show-sql: false
logging:
  level:
    ROOT: error
    com:
      cardaddy:
        batch:
          listener: error
          job:
            processors: error
            writer: debug
            tasklet: info
    org:
      hibernate:
        SQL: error
      springframework: error
