spring:
  jpa:
    properties:
      hibernate:
        search:
          backend:
            aws:
              signing:
                enabled: true
              region: ${AWS_REGION}
              credentials:
                type: static
                access_key_id: ${AWS_ACCESS_KEY_ID}
                secret_access_key: ${AWS_SECRET_ACCESS_KEY}
logging:
  level:
    ROOT: error
    com:
      cardaddy:
        batch:
          listener: error
          job:
            processors: error
            writer: info
            tasklet: debug
    org:
      hibernate:
        SQL: error
      springframework: error
