spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:cardaddy}?useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
    show-sql: false
  batch:
    jdbc:
      initialize-schema: always
logging:
  level:
    ROOT: error
    com.cardaddy.batch: debug
    org:
      hibernate:
        SQL: error
      springframework: error
cardaddy:
  import:
    job-id: ${IMPORT_JOB_ID:1}
