logging:
  level:
    ROOT: error
    com:
      cardaddy:
        batch: debug
        batch.listener: error
        batch.job.processors: error
        batch.job.writer: debug
        batch.ob.tasklet: debug
    org:
      hibernate:
        SQL: error
      springframework: error
