spring:
  jpa:
    properties:
      hibernate:
        search:
          backend:
            aws:
              signing:
                enabled: true
              region: ${AWS_REGION:us-east-1}
              credentials:
                type: static
                access_key_id: ${AWS_ACCESS_KEY_ID:AKIA5X3IEG74BTKKCQ52}
                secret_access_key: ${AWS_SECRET_ACCESS_KEY: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}
logging:
  level:
    ROOT: error
    com:
      cardaddy:
        batch:
          listener: error
          job:
            processors: error
            writer: info
            tasklet: info
    org:
      hibernate:
        SQL: error
      springframework: error
