spring:
  jpa:
    properties:
      hibernate:
        search:
          backend:
            uris: http://localhost:9200
    show-sql: false
ogging:
  level:
    ROOT: error
    com:
      cardaddy:
        batch: debug
        batch.listener: error
        batch.job.processors: error
        batch.job.writer: debug
        batch.ob.tasklet: debug
    org:
      hibernate:
        SQL: error
      springframework: error
