spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:cardaddy.cmfwd2v5fdjs.us-east-1.rds.amazonaws.com}:${MYSQL_PORT:3306}/${MYSQL_DB:cardaddy}
    username: ${MYSQL_USERNAME:cardaddy_search_user}
    password: ${MYSQL_PASSWORD:f_B4rHYbq?Dsx85%FBN53nREF/YWzw}
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  jpa:
    show-sql: false
    properties:
      rewriteBatchedStatements: true
      withcachePrepStmts: true
      useServerPrepStmts: true
      serverTimezone: UTC
      useSSL: false
      hibernate:
        jdbc:
          batch_size: 30
          order_inserts: true
          order_updates: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        search:
          backend:
            uris: ${AWS_OPENSEARCH_URIS:https://search-cardaddy-search-x4exyj2l24mf5of3pto5nt5tvm.us-east-1.es.amazonaws.com}
            analysis:
              configurer: com.cardaddy.batch.CardaddyElasticsearchAnalysisConfigurer
          schema_management:
            strategy: create-or-update

ftp:
  root: ${FTP_ROOT:/ftp}
