spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:cardaddy}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:password}
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  jpa:
    show-sql: false
    properties:
      rewriteBatchedStatements: true
      withcachePrepStmts: true
      useServerPrepStmts: true
      serverTimezone: UTC
      useSSL: false
      hibernate:
        jdbc:
          batch_size: 30
          order_inserts: true
          order_updates: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        search:
          backend:
            uris: http://localhost:9200
            analysis:
              configurer: com.cardaddy.batch.CardaddyElasticsearchAnalysisConfigurer
          schema_management:
            strategy: create-or-update

ftp:
  root: ${FTP_ROOT:/ftp}
#logging:
#  level:
#    ROOT: error
#    com.cardaddy.batch: debug
#    org:
#      hibernate:
#        SQL: error
#      springframework: error
